name: Lint and Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt

      - name: Run clippy (lint)
        run: cargo clippy --all-targets -- -D warnings

      - name: Check formatting
        run: cargo fmt --all -- --check

